// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xdzmxtmcmalwzruidlwy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhkem14dG1jbWFsd3pydWlkbHd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxODEwMjIsImV4cCI6MjA2NDc1NzAyMn0.Ue0JRe9J-f6eXdsn-gn1Y7t-PemKyDCurRWR53bJXUI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});